dist: bionic
language: cpp

addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz

before_script:
- sudo apt-get install libgtest-dev build-essential cmake -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd -

script:
- doxygen Doxyfile
- cmake .
- cmake --build .
- cmake --build . --target package

deploy:

- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    all_branches: true
  local_dir: ./docs/html